name: Generate Keystore

on:
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Keystore
        run: |
          keytool -genkey -v \
            -keystore eyecare.keystore \
            -alias eyecare \
            -keyalg RSA \
            -keysize 2048 \
            -validity 10000 \
            -storepass eyecare123 \
            -keypass eyecare123 \
            -dname "CN=Firhan Studio, OU=Mobile, O=Firhan Studio, L=Pattani, S=Pattani, C=TH"
          base64 eyecare.keystore > eyecare-keystore-base64.txt
          cat eyecare-keystore-base64.txt

      - name: Upload Keystore
        uses: actions/upload-artifact@v4
        with:
          name: keystore
          path: eyecare-keystore-base64.txt
